### ISSUE TITLE
Sierra problems

### ISSUE THREAD

**Issue by amcgilloway** [codeclan/laptop#21]
Can we amend the recommended MacBook specs so that the OS should be High Sierra. Lot of problems with gem installs, Maven projects for Java, etc because a lot of students still on Sierra and needing latest versions of these.

**Comment by johnmcc** [comment]
I'm still on Sierra too. Should we all be upgrading then?

**Comment by CraigMorton** [comment]
I don't know if this is an issue with the laptop script.

I believe the Macbook specs that we hand out to students now ask for "latest macOS version".

The [Meet Your Cohort document](https://github.com/codeclan/instructor_resources/blob/master/Meet%20Your%20Cohort.md) currently says El Cap / Sierra. I've just [put a PR in](https://github.com/codeclan/instructor_resources/pull/5) to update that.

What is it that's happening with the Gem / Maven installs? I assume the students have different versions of `gem` and `maven` than the instructors. I wouldn't have thought that would cause huge problems though.

So the latest versions of gem and maven are not available on macOS Sierra on lower?

**Comment by amcgilloway** [comment]
A lot of gems are failing. Pry, minitest etc Mainly seems to be xcode that is culprit but only happening on sierra laptops. Also issues with psql versions as well. With Maven, laptops on sierra sometimes cant use maven projects built in HS.

**Comment by CraigMorton** [comment]
Ah, so it could be xcode's devtools not being installed / license not being accepted that's causing the gem problems. I don't think we can do this automatically in the script because you can't make people accept a legal agreement with apple.

We need to make sure that all students running the script have the information presented very clearly that: When the pop-up comes up asking about installing xcode dev-tools / accepting the xcode devtools license, they need to do that. I'll speak to Steph and/or Emily about the document that goes out with instructions on running the script.

Alan I think that's a discussion for a different forum, the info on our minimum specs for students laptop's isn't in this repo. (I believe it's with Steph / Emily) My first instinct is I never want to touch a computer running the OS's **minimum** specs. It could be a situation where you open google chrome (or anything) on top of the OS and you're out of memory instantly.

**Comment by CraigMorton** [comment]
I spoke to Emily about the instructions students are given on running this script on their own laptops. The instructions include that they must be running the latest version of the OS. And explains that the should install / update xcode and accept the license agreement before running the script. Maybe these points need to be more obvious / emphasised in that document, but they are there.

Are the problems from students using their own laptops or those renting laptops from us?

**Comment by abazlinton** [comment]
Mojave came out on Monday. All E26 students had High Sierra at MYC. I say we dump support for Sierra. We'll need to update the README.md.

**Comment by CraigMorton** [comment]
I believe this issue should be largely resolved by #27 and some improvements to the README. THe accompanying document with instructions on running the script should now refer to the script's README and the script itself will enforce devtools install before continuing.
